import { useNavigate } from 'react-router-dom';
import { motion } from 'motion/react';
import { ArrowRight } from 'lucide-react';
import PageHeader from '../components/PageHeader';

// Statistics for perceived scale
const collectionStats = [
  { value: '312', label: 'Fossil Specimens', sub: 'catalogued & verified' },
  { value: '47,000+', label: 'Research Hours', sub: 'invested annually' },
  { value: '139', label: 'Years of Operation', sub: 'since 1887' },
  { value: '6', label: 'Continents', sub: 'excavation sites' },
  { value: '28', label: 'Nations', sub: 'international partnerships' },
  { value: '66M', label: 'Years of History', sub: 'on permanent display' },
  { value: '19', label: 'PhD Curators', sub: 'active researchers' },
  { value: '4.2M', label: 'Annual Visitors', sub: 'across all galleries' },
];

// Museum Wings — the institution's physical structure
const museumWings = [
  {
    number: '01',
    name: 'The Theropod Hall',
    era: 'Cretaceous & Jurassic',
    description: "Home to the museum's most dramatic specimens — bipedal carnivores from the agile Velociraptor to the incomprehensible scale of Tyrannosaurus Rex. The hall's centrepiece is a fully articulated T-Rex skeleton suspended mid-stride.",
    highlights: ['Tyrannosaurus Rex', 'Spinosaurus', 'Allosaurus', 'Velociraptor'],
    area: '3,200 m²',
  },
  {
    number: '02',
    name: 'The Sauropod Gallery',
    era: 'Jurassic',
    description: "A cathedral-like space designed to convey the true scale of Earth's largest land animals. Visitors walk beneath a life-size skeletal reconstruction of Brachiosaurus — its neck extending 16 metres above the gallery floor.",
    highlights: ['Brachiosaurus', 'Diplodocus', 'Supersaurus (cast)', 'Argentinosaurus (scale model)'],
    area: '4,800 m²',
  },
  {
    number: '03',
    name: 'The Armoured Creatures Annex',
    era: 'Cretaceous & Jurassic',
    description: 'Dedicated to the defensive masterpieces of dinosaur evolution — from the diamond-plated Stegosaurus to the living tank of Ankylosaurus. Interactive displays allow visitors to examine the physics of the Ankylosaurus tail club.',
    highlights: ['Ankylosaurus', 'Stegosaurus', 'Triceratops', 'Protoceratops'],
    area: '2,100 m²',
  },
  {
    number: '04',
    name: 'Hadrosaur & Social Hall',
    era: 'Late Cretaceous',
    description: "Exploring the most socially complex dinosaurs ever discovered. The acoustic chamber recreates the resonant calls of Parasaurolophus, produced by modelling the exact internal geometry of the crest's nasal passages.",
    highlights: ['Parasaurolophus', 'Pachycephalosaurus', 'Maiasaura', 'Edmontosaurus'],
    area: '1,900 m²',
  },
  {
    number: '05',
    name: 'The Sky Reptiles Gallery',
    era: 'Cretaceous',
    description: 'Suspended from the ceiling of this open-air atrium: a full-scale reconstruction of Pteranodon in flight, its 7-metre wingspan casting a dramatic shadow across the gallery below. A reminder that the Mesozoic sky was as extraordinary as its land.',
    highlights: ['Pteranodon', 'Quetzalcoatlus (scale)', 'Dimorphodon', 'Archaeopteryx (transitional)'],
    area: '2,600 m²',
  },
];

// Scientific highlights — landmark discoveries
const scientificHighlights = [
  {
    year: '2018',
    title: 'Spinosaurus Locomotion Study',
    journal: 'Nature, Vol. 554',
    description: "Our research team's analysis of Spinosaurus bone density confirmed for the first time that a large theropod dinosaur was adapted for sustained aquatic locomotion — rewriting our understanding of dinosaur ecology.",
  },
  {
    year: '2021',
    title: 'T-Rex Growth Rate Analysis',
    journal: 'Science Advances',
    description: 'Cross-sectional analysis of femur bone rings from our primary T-Rex specimen revealed that juveniles grew at rates comparable to modern large mammals — challenging the assumption of reptilian-style slow growth.',
  },
  {
    year: '2023',
    title: 'Ankylosaurus Tail-Club Biomechanics',
    journal: 'PeerJ Palaeontology',
    description: 'Using our CT-scanned Ankylosaurus specimen, the team modelled the mechanical forces generated by the tail club — confirming it could generate impacts sufficient to fracture the cortical bone of large theropods.',
  },
  {
    year: '2024',
    title: 'Parasaurolophus Acoustic Reconstruction',
    journal: 'Cretaceous Research',
    description: 'The complete acoustic modelling of the Parasaurolophus nasal crest, produced entirely from our specimen, generated the first scientifically grounded reconstruction of the calls of a non-avian dinosaur.',
  },
];

// Featured discoveries — recent acquisitions
const featuredDiscoveries = [
  {
    id: 'sue-cast',
    label: 'Recent Acquisition',
    title: '"Helena" — New T-Rex Specimen',
    location: 'Hell Creek Formation, Montana · Excavated 2022',
    description: 'A 94%-complete Tyrannosaurus Rex skeleton — the most complete specimen in our collection and only the third time a T-Rex skull has been found in full articulation. Currently undergoing preparation in our public lab.',
    status: 'In Preparation',
    statusColor: 'text-[#E8C547]',
  },
  {
    id: 'diplodocus-new',
    label: 'New Research',
    title: 'Morrison Formation Survey',
    location: 'Uinta County, Wyoming · Field Season 2023–2025',
    description: 'An ongoing multi-year excavation in the Morrison Formation has yielded over 40 new specimens, including a near-complete juvenile Diplodocus — the first juvenile of this species to be found with a complete skull.',
    status: 'Active Excavation',
    statusColor: 'text-[#D35400]',
  },
  {
    id: 'chinese-partnership',
    label: 'International Partnership',
    title: 'Gobi Desert Feathered Theropods',
    location: 'Djadokhta Formation, Mongolia · Partnership 2024',
    description: 'A five-year research agreement with the Mongolian Institute of Palaeontology grants our curators exclusive study access to a new cache of feathered theropod specimens — among the most significant finds of the decade.',
    status: 'Research Ongoing',
    statusColor: 'text-[#E8C547]',
  },
];

const values = [
  {
    number: '01',
    title: 'Scientific Rigour',
    description: 'Every specimen in our collection has been identified, catalogued, and verified by practising palaeontologists. We do not display reconstructions without disclosing them.',
  },
  {
    number: '02',
    title: 'Public Education',
    description: 'Our mission is to make the deep history of our planet accessible to everyone — children, students, researchers, and curious minds of all backgrounds.',
  },
  {
    number: '03',
    title: 'Ethical Collection',
    description: 'We work exclusively with legally excavated specimens and have returned fossils to countries of origin where international law requires it.',
  },
  {
    number: '04',
    title: 'Living Research',
    description: 'Our curators publish peer-reviewed research annually. The museum is not merely a display — it is an active centre of scientific discovery.',
  },
];

const team = [
  {
    name: 'Dr. Eleanor Marsh',
    role: 'Chief Curator, Dinosaur Halls',
    speciality: 'Theropod Biomechanics & Behaviour',
    note: '28 years of excavation across Montana, Patagonia, and the Gobi Desert. Lead author of the 2021 T-Rex growth rate paper in Science Advances.',
  },
  {
    name: 'Prof. James Okafor',
    role: 'Head of Palaeobotany',
    speciality: 'Cretaceous Ecosystem Reconstruction',
    note: 'Pioneered research on Cretaceous forest ecosystems and their role in dinosaur ecology. Oxford chair of palaeoclimate studies.',
  },
  {
    name: 'Dr. Yuki Tanaka',
    role: 'Restoration Lead',
    speciality: 'Fossil Preparation & Conservation',
    note: "Developed the museum's landmark sand-preservation technique for fragile Jurassic bone material. Restored over 80 specimens to display-ready condition.",
  },
  {
    name: 'Dr. Amara Santos',
    role: 'Field Director',
    speciality: 'Excavation & Acquisition',
    note: 'Oversaw the 2022 discovery of the "Helena" T-Rex specimen. Has directed field seasons across seven countries since 2008.',
  },
  {
    name: 'Prof. Wei Zhang',
    role: 'Director of International Research',
    speciality: 'Feathered Theropod Evolution',
    note: 'Co-leading the Gobi Desert feathered theropod survey. Visiting professor at Peking University and the Mongolian Institute of Palaeontology.',
  },
];

export default function AboutPage() {
  const navigate = useNavigate();

  return (
    <main className="min-h-screen bg-[#151210] text-[#F5F2EA] overflow-x-hidden">
      <title>About — Natural History Museum</title>

      <PageHeader />

      {/* ── HERO ── */}
      <section className="px-6 md:px-16 pt-12 pb-20 border-b border-[#F5F2EA]/10">
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, ease: 'easeOut', delay: 0.1 }}
        >
          <span className="text-[14px] font-mono tracking-[0.3em] uppercase text-[#E8C547] block mb-4">
            [ 04 ] About the Museum
          </span>
          <h1
            className="font-serif font-normal tracking-tight text-[#F5F2EA]"
            style={{ fontSize: 'clamp(3rem, 6.5vw, 6.5rem)', lineHeight: 1.05 }}
          >
            WE DON'T JUST<br />DISPLAY FOSSILS.<br />WE SHARE<br />
            <span className="font-script text-[#E8C547] text-[1.4em] lowercase normal-case italic block md:inline-block md:translate-y-2 mt-1">earth's story</span>
          </h1>
          <p className="text-[#D8D1C2] mt-8 font-mono max-w-lg leading-relaxed text-[16px] md:text-[18px]">
            Founded 1887. One of the world's foremost palaeontological institutions. 312 verified specimens. 19 active research curators. Five permanent wings.
          </p>
        </motion.div>
      </section>

      {/* ── COLLECTION STATISTICS (Bento boxes like in the video) ── */}
      <section className="border-b border-[#F5F2EA]/10" aria-label="Collection statistics">
        <div className="px-6 md:px-16 pt-16 pb-8">
          <motion.h2
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="text-[14px] font-mono tracking-widest uppercase text-[#E8C547] mb-12"
          >
            Collection at a Glance
          </motion.h2>
        </div>
        <div className="grid grid-cols-2 md:grid-cols-4 font-mono">
          {collectionStats.map(({ value, label, sub }, i) => (
            <motion.div
              key={label}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: i * 0.06 }}
              className={`px-6 md:px-10 py-10 flex flex-col gap-1 border-b border-[#F5F2EA]/10
                ${i % 4 !== 3 ? 'md:border-r border-[#F5F2EA]/10' : ''} ${i % 2 !== 1 ? 'border-r md:border-r-0 border-[#F5F2EA]/10' : ''}`}
            >
              <span
                className="font-serif font-normal tracking-tight text-[#F5F2EA]"
                style={{ fontSize: 'clamp(2.2rem, 3.5vw, 3.5rem)', lineHeight: 1.1 }}
              >
                {value}
              </span>
              <span className="text-[14px] tracking-widest uppercase text-[#E8C547]">{label}</span>
              <span className="text-[13px] text-[#A9A295]">{sub}</span>
            </motion.div>
          ))}
        </div>
      </section>

      {/* ── MISSION ── */}
      <section className="grid md:grid-cols-2 border-b border-[#F5F2EA]/10">
        <motion.div
          initial={{ opacity: 0, x: -24 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.7, ease: 'easeOut' }}
          className="px-6 md:px-16 py-16 border-b md:border-b-0 md:border-r border-[#F5F2EA]/10 font-mono"
        >
          <h2 className="text-[14px] tracking-widest uppercase text-[#E8C547] mb-6">Our Mission</h2>
          <p className="text-[#D8D1C2] leading-[1.8] mb-6 text-[16px] md:text-[18px]">
            The Natural History Museum exists to preserve, study, and communicate the story of life on Earth. Founded in 1887, we hold one of the most significant palaeontological collections in the world — over 312 catalogued specimens spanning the full breadth of the Mesozoic Era.
          </p>
          <p className="text-[#A9A295] leading-[1.8] text-[16px] md:text-[18px]">
            We believe that understanding deep time is one of the most important things a society can do. The history of life on Earth provides context for everything — the fragility of ecosystems, the mechanisms of extinction, and the extraordinary improbability of our own existence.
          </p>
        </motion.div>
        <motion.div
          initial={{ opacity: 0, x: 24 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.7, ease: 'easeOut', delay: 0.1 }}
          className="px-6 md:px-16 py-16 font-mono"
        >
          <h2 className="text-[14px] tracking-widest uppercase text-[#E8C547] mb-6">History</h2>
          <p className="text-[#D8D1C2] leading-[1.8] text-[16px] md:text-[18px]">
            Established during the great age of palaeontological discovery, the museum originally housed seven specimens donated by private collectors. Over 139 years, through fieldwork on every continent, academic partnerships, and international loans, that collection has grown to 312 verified specimens and tens of thousands of associated flora and invertebrate fossils.
          </p>
          <p className="text-[#A9A295] leading-[1.8] mt-4 text-[16px] md:text-[18px]">
            The permanent exhibition — "The Age of Dinosaurs" — opened in 2018 following a six-year renovation of the main fossil halls. A second phase of expansion, adding two new wings and a public preparation laboratory, is scheduled for completion in 2027.
          </p>
        </motion.div>
      </section>

      {/* ── MUSEUM WINGS (Bento rows like in the video) ── */}
      <section className="border-b border-[#F5F2EA]/10">
        <div className="px-6 md:px-16 pt-16 pb-8">
          <motion.h2
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="text-[14px] font-mono tracking-widest uppercase text-[#E8C547] mb-2"
          >
            Five Permanent Wings
          </motion.h2>
          <motion.p
            initial={{ opacity: 0, y: 12 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, delay: 0.1 }}
            className="text-[#A9A295] font-mono text-[14px]"
          >
            14,600 m² of permanent exhibition space
          </motion.p>
        </div>
        <div className="flex flex-col">
          {museumWings.map((wing, i) => {
            const isEven = i % 2 === 0;
            return (
              <motion.div
                key={wing.number}
                initial={{ opacity: 0, y: 24 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.55, delay: i * 0.08 }}
                className={`border-t border-[#F5F2EA]/10 px-6 md:px-16 py-10 grid md:grid-cols-[auto_1fr_auto] gap-8 md:gap-16 items-start
                  ${isEven ? 'bg-[#F5F2EA] text-[#151210]' : 'bg-[#1A1614] text-[#F5F2EA]'}`}
              >
                {/* Number */}
                <div className="shrink-0">
                  <span className={`text-[14px] font-mono tracking-widest ${isEven ? 'text-[#D35400]' : 'text-[#E8C547]'}`}>
                    {wing.number}
                  </span>
                </div>
                {/* Content */}
                <div>
                  <div className="flex flex-col md:flex-row md:items-baseline gap-2 md:gap-6 mb-4">
                    <h3
                      className="font-serif font-normal tracking-tight"
                      style={{ fontSize: 'clamp(1.6rem, 2.5vw, 2.2rem)', lineHeight: 1.2 }}
                    >
                      {wing.name}
                    </h3>
                    <span className={`text-[13px] font-mono tracking-widest uppercase ${isEven ? 'text-[#151210]/60' : 'text-[#A9A295]'}`}>
                      {wing.era}
                    </span>
                  </div>
                  <p className="text-[16px] md:text-[18px] leading-relaxed mb-6 max-w-2xl font-mono">
                    {wing.description}
                  </p>
                  <div className="flex flex-wrap gap-2">
                    {wing.highlights.map(h => (
                      <span
                        key={h}
                        className={`text-[13px] font-mono tracking-widest uppercase border px-2.5 py-1 rounded-sm
                          ${isEven 
                            ? 'border-[#151210]/15 text-[#151210] bg-black/5' 
                            : 'border-[#F5F2EA]/10 text-[#A9A295] bg-black/20'}`}
                      >
                        {h}
                      </span>
                    ))}
                  </div>
                </div>
                {/* Area */}
                <div className="shrink-0 text-right hidden md:block">
                  <span className={`text-[14px] font-mono tracking-widest ${isEven ? 'text-[#151210]/60' : 'text-[#A9A295]'}`}>
                    {wing.area}
                  </span>
                </div>
              </motion.div>
            );
          })}
        </div>
      </section>

      {/* ── FEATURED DISCOVERIES ── */}
      <section className="px-6 md:px-16 py-16 border-b border-[#F5F2EA]/10">
        <motion.h2
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-[14px] font-mono tracking-widest uppercase text-[#E8C547] mb-12"
        >
          Recent Discoveries &amp; Acquisitions
        </motion.h2>
        <div className="flex flex-col">
          {featuredDiscoveries.map(({ label, title, location, description, status, statusColor }, i) => (
            <motion.div
              key={title}
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: i * 0.1 }}
              className="flex flex-col md:flex-row gap-8 md:gap-16 py-10 border-b border-[#F5F2EA]/10 last:border-b-0"
            >
              <div className="md:w-[220px] shrink-0 font-mono">
                <span className="text-[13px] tracking-widest uppercase text-[#A9A295] block mb-2">{label}</span>
                <span className={`text-[13px] tracking-widest uppercase ${statusColor}`}>{status}</span>
              </div>
              <div className="flex-1 font-mono">
                <h3 className="font-serif font-normal text-[#F5F2EA] mb-1 text-[24px] md:text-[28px] leading-tight">
                  {title}
                </h3>
                <p className="text-[13px] tracking-widest uppercase text-[#A9A295] mb-4">{location}</p>
                <p className="text-[16px] md:text-[18px] text-[#D8D1C2] leading-relaxed max-w-2xl">{description}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* ── SCIENTIFIC HIGHLIGHTS (Typewriter Cards) ── */}
      <section className="px-6 md:px-16 py-16 border-b border-[#F5F2EA]/10">
        <motion.h2
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-[14px] font-mono tracking-widest uppercase text-[#E8C547] mb-12"
        >
          Scientific Publications &amp; Highlights
        </motion.h2>
        <div className="grid md:grid-cols-2 gap-6 font-mono">
          {scientificHighlights.map(({ year, title, journal, description }, i) => (
            <motion.div
              key={title}
              initial={{ opacity: 0, y: 24 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: i * 0.08 }}
              className="border border-[#F5F2EA]/10 bg-[#1A1614]/60 p-8 hover:border-[#E8C547]/40 transition-colors duration-300"
            >
              <div className="flex items-start justify-between mb-4">
                <span className="text-[13px] tracking-widest uppercase text-[#A9A295]">{year}</span>
                <span className="text-[12px] tracking-widest text-[#E8C547] text-right">{journal}</span>
              </div>
              <h3 className="font-serif font-normal text-[#F5F2EA] mb-3 text-[22px] md:text-[24px] leading-tight">
                {title}
              </h3>
              <p className="text-[15px] md:text-[16px] text-[#D8D1C2] leading-relaxed">{description}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* ── VALUES (Bento Grid cards) ── */}
      <section className="px-6 md:px-16 py-16 border-b border-[#F5F2EA]/10">
        <motion.h2
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-[14px] font-mono tracking-widest uppercase text-[#E8C547] mb-12"
        >
          What We Stand For
        </motion.h2>
        <div className="grid md:grid-cols-2 gap-6 font-mono">
          {values.map(({ number, title, description }, i) => (
            <motion.div
              key={number}
              initial={{ opacity: 0, y: 24 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: i * 0.08 }}
              className="flex gap-6 p-6 border border-[#F5F2EA]/10 bg-[#1A1614]/30 hover:border-[#E8C547]/30 transition-colors duration-300"
            >
              <span className="text-[14px] tracking-widest text-[#E8C547] shrink-0 mt-1" aria-hidden="true">{number}</span>
              <div>
                <h3 className="font-serif font-normal text-[#F5F2EA] mb-2 text-[22px] md:text-[24px]">{title}</h3>
                <p className="text-[15px] md:text-[16px] text-[#D8D1C2] leading-relaxed">{description}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* ── TEAM ── */}
      <section className="px-6 md:px-16 py-16 border-b border-[#F5F2EA]/10">
        <motion.h2
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-[14px] font-mono tracking-widest uppercase text-[#E8C547] mb-12"
        >
          Our Research Team
        </motion.h2>
        <div className="flex flex-col font-mono">
          {team.map(({ name, role, speciality, note }, i) => (
            <motion.div
              key={name}
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: i * 0.08 }}
              className="flex flex-col md:flex-row md:items-start gap-4 md:gap-16 py-8 border-b border-[#F5F2EA]/10 last:border-b-0"
            >
              <div className="md:w-[280px] shrink-0">
                <p className="font-serif font-normal text-[#F5F2EA] text-[22px] md:text-[24px]">{name}</p>
                <p className="text-[14px] tracking-widest uppercase text-[#E8C547] mt-1">{role}</p>
                <p className="text-[13px] tracking-widest text-[#A9A295] mt-0.5">{speciality}</p>
              </div>
              <p className="text-[16px] md:text-[18px] text-[#D8D1C2] leading-relaxed flex-1">{note}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* ── CTA ── */}
      <section className="px-6 md:px-16 py-20 bg-[#1A1614]/10">
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.7, ease: 'easeOut' }}
          className="max-w-xl font-mono"
        >
          <p className="text-[#D8D1C2] leading-[1.8] mb-8 text-[16px] md:text-[18px]">
            Walk through 252 million years of natural history. Twelve permanent specimens, five wings, and the stories of creatures that shaped the world you're standing in.
          </p>
          <button
            onClick={() => navigate('/exhibits')}
            aria-label="Explore all exhibits"
            className="group flex items-center gap-4 border border-[#E8C547]/20 bg-[#151210] px-8 py-4 hover:border-[#E8C547] hover:bg-[#E8C547]/10 text-[#D8D1C2] hover:text-[#F5F2EA] transition-all duration-300 cursor-pointer
              focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"
          >
            <span className="text-[14px] tracking-widest uppercase">Explore the Collection</span>
            <ArrowRight size={14} strokeWidth={1.5} className="group-hover:translate-x-1 transition-transform duration-300" aria-hidden="true" />
          </button>
        </motion.div>
      </section>

      <div className="px-8 py-8 border-t border-[#F5F2EA]/15 flex flex-col md:flex-row md:items-center md:justify-between gap-2 bg-[#151210]">
        <p className="font-mono tracking-widest text-[#A9A295] uppercase text-[12px]">
          NATURAL HISTORY MUSEUM — EST. 1887 (C) 2026
        </p>
        <p className="font-mono tracking-widest text-[#A9A295]/80 uppercase hidden md:block text-[12px]">
          312 SPECIMENS · 5 WINGS · 14,600 M² · 19 CURATORS
        </p>
      </div>
    </main>
  );
}
